apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: postgres-ui-ingress
  namespace: postgres
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`postgres-ui.mw.local`)
    priority: 10
    services:
    - name: postgres-ui-service
      port: 80
  tls:
    secretName: postgres-ui-tls-secret

