apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress-route
  namespace: cattle-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`rancher.mw.local`)
    priority: 10
    services:
    - name: rancher
      port: 80
  tls:
    secretName: rancher-tls-secret

