rancher:
  

  replicas: 1

  bootstrapPassword: admin123

  hostname: rancher.mw.local
  ingress:
    enabled: true
  tls:
    # options: rancher, letsEncrypt, secret
    source: secret
    secretName: rancher-tls-secret


