apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pypiserver-service
  namespace: pypi
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`pypi.mw.local`)
    priority: 10
    services:
    - name: pypiserver-service
      port: 80
  tls:
    secretName: pypiserver-tls-secret

