apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry-ui
  namespace: docker-registry
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`docker-registry-ui.mw.local`)
      kind: Rule
      services:
        - name: registry-ui
          port: 80
  tls:
    secretName: docker-registry-ui-tls-secret

