apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  labels:
    app: vaultwarden
spec:
  ports:
    - port: 80
      targetPort: 443
  selector:
    app: vaultwarden
  type: ClusterIP
