apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress-route
  namespace: monitoring
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`prometheus.mw.local`)
    priority: 10
    services:
    - name: prometheus-service
      port: 80
  tls:
    secretName: prometheus-tls-secret

