apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: grafana
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  dnsNames:
    - grafana.mw.local
  duration: 8760h
  renewBefore: 720h
