

deployment:
  nameOverride: argo-workflow
  fullnameOverride: argo-workflow
  server:
    extraArgs: ["--auth-mode=server"]
    ingress:
      enabled: true  # Enable the ingress resource
      annotations:   # Add any necessary annotations here
        traefik.ingress.kubernetes.io/frontend-entry-points: "https"
      hosts:
        - argo-workflow.mw.local  # Specify your desired hostname
      tls:
        - secretName: argocd-workflow-tls-secret