apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docker-registry
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`docker-registry.mw.local`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: docker-registry-service
      port: 5000
  tls:
    secretName: docker-registry-tls-secret

