apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare
data:
  config.yaml: |
    # ConfigMap
    tunnel: homelab
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      - service: http://pejzen-frontend.pejzen.svc.cluster.local:80
        hostname: "*"
      - service: http_status:404
