apiVersion: v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
      name: cloudflare-tunnel
    spec:
      containers:
        - name: cloudflare-tunnel
          image: cloudflare/cloudflared:2025.11.1-arm64
          imagePullPolicy: IfNotPresent
          args: 
            - "tunnel"
            - "--url"
            - "http://pejzen.mw.local"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-token
                  key: token

  