apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
  labels:
    app: cloudflare
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
      name: cloudflare-tunnel
    spec:
      containers:
        - name: cloudflare-tunnel
          image: cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          args: 
            - tunnel
            - run
          volumeMounts:
            - name: tunnel-creds
              mountPath: /etc/cloudflared/credentials.json
              subPath: credentials.json
              readOnly: true
            - name: tunnel-config
              mountPath: /etc/cloudflared/config.json
              subPath: config.yaml
              readOnly: True
      volumes:
        - name: tunnel-creds
          secret:
            secretName: cloudflare-tunnel-credentials
        - name: tunnel-config
          ConfigMap:
           name: cloudflare-tunnel-config

       
  