apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
  labels:
    app: cloudflare
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
      name: cloudflare-tunnel
    spec:
      containers:
        - name: cloudflare-tunnel
          image: cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          args: 
            - "tunnel"
            - "--url"
            - "pejzen-frontend.pejzen.svc.cluster.local:80"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-token
                  key: token

  