apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: etcd-ingress
  namespace: catcode
  annotations: {
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  }
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`etcd.mw.local`)
      kind: Rule
      services:
        - name: etcd
          port: 80
          scheme: h2c 

