apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sealed-secrets-web-ingress
  namespace: sealedsecrets
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`sealedsecrets.mw.local`)
    priority: 10
    services:
    - name: sealedsecrets-ui-svc
      port: 80